fix bug with start of file comments
ReplicatorLabs/lua-elementtree pull request #1
Opened 2024-05-24 05:50 UTC by subashch6

refactors the comment parsing code outside of the token code such that token parsing does not restrict the comment parsing code. Prior to this commit the token parsing code would hand the comment parser an invalid token, which might indicate it isn't a comment which is valid or that the token parser failed to parse the next token to contain the entire comment which would result in an invalid state for that token and the program. This change allows the comment code to read a full comment from the entire text string in the file instead of being restricted to the output of the token parser allowing for successful comment parsing.

This code still crashes at this moment as it generates multiple root nodes which the program is next expected to handle. Requesting a review from Alex Barbur on how to proceed.

2024-05-24 05:55 UTC, subashch6 commented
@CtrlC-Root  This commit currently causes the code the fail since the Document "class" cannot proceed with multiple root nodes. How would you wish for me to proceed? I can try to modify the Document "class" is hold on the comments or I can just remove them before creating the Document "class" since we don't really NEED these comment for now, although I would assume we don't want to lose any data in the long run since this is a library we want to use again in the future.

2024-05-25 07:01 UTC, CtrlC-Root requested changes
So this works but is a little inefficient; you are using string `find()` and `match()` to evaluate that expression twice. Instead I would use `find()` to match the opening tag and if found use `find()` to locate the next closing tag. There are fewer invariants to check along the way; for example you are checking if string `match()` returns a capture group for the comment but since `find()` has already matched the same pattern it should always succeed so that should be an assert instead. Look at how leaf text tags like `<script>` are captured for an example of a similar pattern.

Regarding multiple root nodes, yeah the Document class will eventually need to support multiple root nodes, but for now I would just assert we found at least one and use the last one to create the document. Leave a `XXX` comment explaining it as well.

2024-05-25 07:01 UTC, CtrlC-Root commented on elementtree.lua
> +    -- print("start index: " .. start_index)
Dont include commented out code unless there is an explanation alongside to explain why. In this case I would guess debugging so I would drop it.

2024-06-05 11:43 UTC, subashch6 commented on elementtree.lua
> +    -- print("start index: " .. start_index)
removed the comments

2024-06-05 11:44 UTC, subashch6 commented on elementtree.lua
> +    -- print("start index: " .. start_index)
pretty sure the most recent commit address all the concerns in this thread. Ready for review.

2024-06-05 12:44 UTC, CtrlC-Root approved these changes
:rocket:

2024-06-05 12:46 UTC, merged